# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'SW-CollectionView' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SW-CollectionView
  pod 'Alamofire', '~> 3.4.0'
  pod 'Gloss', '~> 0.7.3'
end
